spring.application.name=12-Digital-lib-V1
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_LibraryV1
spring.datasource.username=postgres
spring.datasource.password=Sharu@1112
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true